## start with
##    loadgen benchmark prod-benchmark.yaml

workspaces: 500
ideImage: eu.gcr.io/gitpod-core-dev/build/ide/code:commit-8c1466008dedabe79d82cbb91931a16f7ce7994c
repos:
  - cloneURL: https://github.com/gitpod-io/template-typescript-node/
    # image: gitpod/workspace-mongodb
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:53489ee25aa4d1797edd10485d8ecc2fc7a7456ae37718399a54efb498f7236f
  - cloneURL: https://github.com/gitpod-io/template-typescript-react
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
  - cloneURL: https://github.com/gitpod-io/template-python-django/
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
  - cloneURL: https://github.com/gitpod-io/template-python-flask
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
  - cloneURL: https://github.com/gitpod-io/spring-petclinic/
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
#  - cloneURL: https://github.com/gitpod-io/template-php-drupal-ddev
    # image: (dockerfile)
#    workspaceImage:
#  - cloneURL: https://github.com/gitpod-io/template-php-laravel-mysql
    # image: (dockerfile)
    #workspaceImage:
#  - cloneURL: https://github.com/gitpod-io/template-ruby-on-rails-postgres/
    # image: (dockerfile)
    #workspaceImage:
  - cloneURL: https://github.com/gitpod-io/template-golang-cli/
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
  - cloneURL: https://github.com/gitpod-io/template-rust-cli/
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
  - cloneURL: https://github.com/gitpod-io/template-dotnet-core-cli-csharp/
    # image: gitpod/workspace-dotnet
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:0b62a3c575c8f00b9130f8a6572d9b4fd935e06de4498cef4ec2db8507cd6159
  - cloneURL: https://github.com/gitpod-io/template-sveltejs/
    # image: gitpod/workspace-full:latest
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:63bf2cbae693a7ecf60a40fb1eadc90b83a99919a2a010019a336a81b0c54b84
